#! /bin/bash
#$Author: ee364a09 $
#$Date: 2014-01-14 14:59:46 -0500 (Tue, 14 Jan 2014) $
#$Revision: 63438 $
#$HeadURL: svn+ssh://ece364sv@ecegrid-lnx/home/ecegrid/a/ece364sv/svn/S14/students/ee364a09/Lab01/Script2 $
#$Id: Script2 63438 2014-01-14 19:59:46Z ee364a09 $
Num_Of_Param=$#
Param_Values=$@
#let I=\$1\
for (( I=$1; I>0;I--))
do      
    echo  ${I}
done 
exit 0

